### ISSUE TITLE
predict.MAT weighted mean fails at perfect analogue

### ISSUE THREAD

**Issue by lukasjonkers** [nsj3/rioja#3]
https://github.com/nsj3/rioja/blob/01b87b11f086c2b96106493521eb82dabcae9d46/R/MAT.r#L85
gives NaN when dist.n == 0

I work with planktonic foraminifera datasets where finding perfect analogues can happen in the assemblages with a few species only.

Perhaps dissimilarities/distances below a threshold can be replaced with this threshold similar to what is done in `MAT` https://github.com/nsj3/rioja/blob/01b87b11f086c2b96106493521eb82dabcae9d46/R/MAT.r#L12-L15

**Comment by nsj3** [comment]
Done
