### ISSUE TITLE
The question about LWWA&LWWAPLS

### ISSUE THREAD

**Issue by pax-gong** [nsj3/rioja#5]
Hello author, I have seen LWWA and LWWAPLS in other papers. 
1.Do you know whether these two methods are in other packages?
2. Are these two methods related to WA and WAPLS？
                                                                                          Thank you for taking the time to answer

**Comment by nsj3** [comment]
Dear pax-gong

> Hello author, I have seen LWWA and LWWAPLS in other papers.
> 1.Do you know whether these two methods are in other packages?

I don't know of any other packages that implement these methods.

> 2. Are these two methods related to WA and WAPLS？

Yes, they are locally weighted versions of these methods.  See this book chapter for details:

Juggins, S., and H. J. B. Birks. 2012. Quantitative environmental reconstructions from biological data. Pages 431-494 in H. J. B. Birks, A. F. Lotter, S. Juggins, and J. P. Smol, editors. Tracking Environmental Change Using Lake Sediments: Data Handling and Numerical Techniques. Springer, Dordrecht.

Send me a request on ResearchGate if you have problems getting this chapter:
https://www.researchgate.net/publication/381552048_Quantitative_environmental_reconstructions_from_biological_data

Hope this helps, Steve

**Comment by pax-gong** [comment]
Dear Steve
  Thank you very much for your answer. I will review the information you provided
Pax
